theme: jekyll-theme-cayman
title: Flux.Vote
description: "14 days of coding to get a demo of Flux's voting app live"
google_analytics: UA-62282050-7
github:
  is_project_page: False
buttons:
  - label: "View Livestream"
    href: "https://www.youtube.com/embed/live_stream?channel=UCzbr9m9G05Y5uy3HQuJWAlw"
