theme: jekyll-theme-cayman
title: Flux.Vote
description: "14 days of coding to get a demo of Flux's voting app live"
google_analytics: UA-62282050-7
github:
  is_project_page: False
buttons:
  - label: "View Livestream"
    href: "https://www.youtube.com/channel/UCzbr9m9G05Y5uy3HQuJWAlw/live"
  - label: "GitHub: Code"
    href: "https://github.com/voteflux/voting-alpha"
  - label: "GitHub: Website"
    href: "https://github.com/voteflux/flux-dot-vote"
  - label: "GitHub: Project/Kanban"
    href: "https://github.com/voteflux/flux-dot-vote/projects/2"
  - label: "AWS: Deploy latest stack (DEV)"
    href: "https://console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/new?stackName=test-voting-stack&templateURL=https%3A%2F%2Fs3.ap-southeast-2.amazonaws.com%2Fflux-scratch%2Ftemplates%2Fflux-securevote-voting-stack.yaml"
markdown: kramdown
